version: "3"

services:
  app:
    image: golang:1.11
    volumes:
    - .:$GOPATH/src/github.com/AndreiD/GinBootstrap
    working_dir: $GOPATH/src/github.com/AndreiD/GinBootstrap
    command: go run main.go